- name: start telegram bot service
  systemd:
    name: serviceTelegramBot
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: start stocks monitor service
  systemd:
    name: serviceStocksMonitor
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: start notification monitor service
  systemd:
    name: serviceNotificationMonitor
    state: restarted
    enabled: yes
    daemon_reload: yes