---
- name: "Install git"
  apt:
    name: "git"
    state: "latest"
    update_cache: true

- include: "install-postgresql.yml"

- name: "Install memcached"
  apt:
    name: "memcached"
    state: "latest"
    update_cache: true

- name: "Install cron"
  apt:
    name: "cron"
    state: "latest"
    update_cache: true

- name: "Install python3.9"
  apt:
    name: "python3.9"
    state: "present"
    update_cache: true

- name: "Install pip"
  apt:
    name: "pip"
    state: "latest"
    update_cache: true